@echo off
title Reset & Push Unity Project to GitHub (MaoRunner)
echo ============================================
echo     MAORUNNER - FULL GIT RESET AND PUSH
echo ============================================

REM 1. Удаляем старый .git (если есть)
echo [1/6] Removing old .git folder...
taskkill /f /im git.exe >nul 2>&1
rmdir /s /q .git

REM 2. Инициализация нового репозитория
echo [2/6] Initializing new Git repository...
git init

REM 3. Создаем .gitignore
echo [3/6] Creating .gitignore file...
(
echo # Unity generated
echo [Ll]ibrary/
echo [Tt]emp/
echo [Oo]bj/
echo [Bb]uild*/
echo [Ll]ogs/
echo [Uu]serSettings/
echo [Mm]emoryCaptures/
echo.
echo # VS / Rider
echo .vs/
echo .idea/
echo *.csproj
echo *.sln
echo *.user
echo *.unityproj
echo *.pidb
echo *.suo
echo *.userprefs
echo.
echo # Autogenerated
echo *.apk
echo *.aab
echo *.unitypackage
echo .DS_Store
) > .gitignore

REM 4. Добавляем и коммитим файлы
echo [4/6] Adding and committing project files...
git add .
git commit -m "Clean version v0.3 ready"

REM 5. Подключаем GitHub репозиторий (замени ссылку!)
echo [5/6] Linking GitHub repository...
git branch -M main
git remote add origin https://github.com/arturmaster420/MaoRunner.git

REM 6. Отправляем проект
echo [6/6] Pushing to GitHub...
git push -u origin main --force

echo ============================================
echo         ✅ Done! Check your GitHub.
echo ============================================
pause
